name: pbl_sertifikasi
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  dotted_border: ^2.0.0
  flutter_dash: ^1.0.0
  http: ^0.13.3
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.4+8
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_polinema.png
    - assets/List.png
    - assets/sertifikat.png

