name: project
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.3.2
  http: ^1.1.0
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - asset/logo_polinema.png
    - asset/sertifikat.png
    - asset/List.png
  uses-material-design: true